services:
  client_web:
    build:
      dockerfile: Dockerfile.web
    volumes:
      - shared-volume:/app/dist
    depends_on:
      - client_mobile

  client_mobile:
    build:
      dockerfile: Dockerfile.mobile
    command: cp /workdir/android/app/build/outputs/apk/release/app-release-signed.apk /static/client.apk
    volumes:
      - shared-volume:/static

volumes:
  shared-volume:
